### PR TITLE
Mathjax support

### PR DESCRIPTION
**Pull request by etra0**
Hi panr, first, thanks for your amazing theme.

I would like to add MathJax support since it's quite useful for my blog, and I'm sure every person that wants to write a little bit of math would like to have this as well.

I used [this post](https://divadnojnarg.github.io/blog/mathjax/) as a reference, using the 2nd option but using the cloudflare CDN since the MathJax CDN redirects to that one.

It works out of the box:
```md
$$
\theta \in [0, 2\pi] \\\\
\phi \in [0, \pi] \\\\
r \in [0, \infty[ \\\\
$$
```
image

### CODE REVIEW

**Comment by StevenDoesStuffs** [comment]
Your link is broken, I think you might mean [this post](https://geoffruddock.com/math-typesetting-in-hugo/)? Anyhow, I would love to have mathjax support for this theme. Most themes have katex which doesn't support inline math, and with the deprecation of mmark, that's starting to be sorta an issue. 

One concern might be to have an option to enable it instead, since most people aren't rendering math.

**Comment by TEFEdotCC** [comment]
Please push it to version 3.
http://docs.mathjax.org/en/latest/web/start.html

```html
<!-- Browser Compatibility //-->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<!-- get version 3.x.x //-->
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<!-- example of basic configuration //-->
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
};
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```

Please do only a basic configuration and add an way for simple custom configuration.

**Comment by etra0** [comment]
Sadly, at this point I think this PR is not considered. If there's interest from the author I'll do it.

Cheers.

**Comment by panr** [comment]
Hi, from now new features should be delivered directly from the community. Here's a link to the README section regarding new approach — https://github.com/panr/hugo-theme-hello-friend#feature

**Pull request closed without merging**
