### PR TITLE
Add Cover Credit param to posts

### PR DESCRIPTION
**Pull request by zporter**
## Why?

I wanted to be able to credit a cover image on my blog posts.

## What Changed?

- Added support for a `coverCaption` page variable in the post's front matter.
- Moved the `post-cover` class to a new `<figure>` container.
- Added a `<figcaption>` tag if `coverCaption` was specified.
- Moved the `box-shadow` CSS specification to the `post-cover`'s `img` tag so the caption didn't have a different bg color from the rest of the page.

## Screenshot

Screen Shot 2020-07-04 at 9 47 28 AM

### CODE REVIEW

**Comment by aormsby** [comment]
I didn't look at the implementation, but I do like this idea. My only suggestion might be to name the param something more like "coverDescription" / "coverDetails" / "coverSubtitle"... something like that since it may not always be a photo credit and just a general message. My two cents.

**Comment by panr** [comment]
`coverCaption`?

**Comment by zporter** [comment]
@aormsby / @panr --

I can be talked into `coverCaption`. An earlier implementation used this based on [the `figure` shortcode](https://github.com/panr/hugo-theme-hello-friend#built-in-shortcodes). I updated to "credit" because I felt that closer reflected the use-case, but I can see the argument to make it a bit more generic so it can be used for a variety of cases. I'll make that edit to be a bit more generic and consistent with the `figure` shortcode 👍

**Comment by SurajVerma** [comment]
Cover credits are a good to have feature. I am using my own implementation for the same. As I am new to Hugo ecosystem so my implementation may be naive hence I didn't dare to create a PR :face_with_head_bandage: . And then today I saw there is already a PR for this. :smile:

Here is how my implementation looks like on front end.

image

**Comment by SurajVerma** [comment]
Cover credits are a good to have feature. I implemented this on my blog last week (on 29th June to be precise) and as I am new to Hugo ecosystem so thinking my implementation may be naive I didn't dare to create a PR :face_with_head_bandage: . And then today I saw there is already a PR for this. :smile:. Only difference here is I am using a `span` instead of `figcaption` and `coverCredit` instead of `coverCaption`.

Here is how my implementation looks like on front end.

image

**Comment by SurajVerma** [comment]
Cover credits are a good to have feature. I implemented this on my blog last week (on 29th June to be precise) and as I am new to Hugo ecosystem so thinking my implementation may be naive I didn't dare to create a PR :face_with_head_bandage: . And then today I saw there is already a PR for this. :smile:. Only two small differences in my implementation, first,  I am using a `span` instead of `figcaption` (as I am not using `figure` container) and second `coverCredit` instead of `coverCaption`.

Here is how my implementation looks like on front end.

image

**Comment by panr** [comment]
Love it @zporter! Thanks for the PR, I have nothing to add — I'm merging it 🎉

**Pull request merged**
