### PR TITLE
taxonomy added

### PR DESCRIPTION
**Pull request by SerhatTeker**
First of all thanks for this great theme, really appreciate it.

I think someone could need `taxonomy`, especially `tags`, as I do if she/he writes a "technical" blog.  I added templates and updated `README` accordingly. Couldn't fit explanations in one line as you do in the actual `add-ons` section. But if it is a necessity I will try to find a way.

Also added myself as a "USERS" as well.

### CODE REVIEW

**Comment by thomasjsn** [comment]
I think the `layouts/taxonomy/list.html` is very useful, but I like the way it shows tagged pages now.

**Comment by thomasjsn** [comment]
I quite like how tagged posts are shown, but I think the terms index is a nice addition :) I copied the `layouts/taxonomy/list.html` into `layouts/_default/terms.html` on my website.

**Comment by SerhatTeker** [comment]
Sorry, what is terms index? Couldn't find the `layouts/_default/terms.html` in the [curent master:`40b5b2b`](https://github.com/panr/hugo-theme-hello-friend/tree/40b5b2b887130fcd1d975a1752a8dbeff1aeb5b3).

 Is there already a way to show `list/single` `taxonomy` to show? Couldn't figured out before.

**Comment by thomasjsn** [comment]
@SerhatTeker A terms index is the `/tags` or `/categories`, or any other taxonomy, page. You are right, the theme doesn't include a `layouts/_default/terms.html` page, which is why `/tags` and `/categories` pages did not exist.

The theme does, however, support `/tags/tag` and `/categories/category` pages. Just make sure your Hugo install is up to date :)

I took only the terms index page you created and submitted it as PR #93.

**Comment by SerhatTeker** [comment]
@thomasjsn I see. I thought it was another thing and couldn't find in hugo documentation too. But it is `taxonomy terms` we're talking about :)

I wasn't happy with my solution since we have to create 2 different `layout` for `tags` and `categories`. Your solution goes better with the theme "minimal" concept. So I updated my fork accordingly. Thanks a lot.

P.S: I still prefer `archive` layout instead of default `terms`/`list` but handle it my local `layout` :)

**Pull request closed without merging**
