### PR TITLE
added archives page, made the posts timestamps more human-readable

### PR DESCRIPTION
**Pull request by wieueberall**
### What has changed:

Refering to #26  I made a pull request containing the requested changes. If you want to, feel free to keep the changes making the posts timestamps more human-readable as well.

### Appendix: Screenshot

image

### CODE REVIEW

**Comment by jhabdas** [comment]
I'd really like to get a look at that GDPR page? Where can I find the above site?

**Comment by jhabdas** [comment]
I'd really like to get a look at that GDPR page. Where can I find the above site? 🍶

**Comment by jhabdas** [comment]
nm xD https://huffleclaw.org

**Comment by wieueberall** [comment]
@jhabdas The GDPR page is pretty basic & only stating that my set-up does not involve processes being affected by the GDPR. However if you have questions concerning GDPR and internet law, feel free to ask, I've got quite some experience in that field and am happy to help.

**Comment by pard68** [comment]
Thanks for this! I really appreciate this and have replaced `/post` with this.

I did notice a few issues with this though. 

The partial `head.html`, by default is empty. It is more for adding additions to the head than the proper head elements. You could add the contents needed to `head.html` and this would resolve it, however that is contra to the parent's design. So, my suggested fix, and what I have done on my fork is:

```
<!DOCTYPE html>
<html lang="{{ $.Site.Language }}">
<head>
  {{ block "title" . }}
    <title>{{ if .IsHome }}{{ $.Site.Title }}{{ with $.Site.Params.Subtitle }} — {{ . }}{{ end }}{{ else }}{{ .Title }} :: {{ $.Site.Title }}{{ with $.Site.Params.Subtitle }} — {{ . }}{{ end }}{{ end }}</title>
  {{ end }}
  {{ partial "head.html" . }}
</head>
 <script src="//instant.page/1.2.1" type="module" integrity="sha384-/IkE5iZAM/RxPto8B0nvKlMzIyCWtYocF01PbGGp1qElJuxv9J4whdWBRtzZltWn"></script> 
<body class="{{ if ne $.Site.Params.defaultTheme "light" -}} dark-theme {{- end -}}">
  {{ partial "header.html" . }}
<div class="content">
    <div class="inner">
        {{ range (.Site.RegularPages.GroupByDate "2006") }}
            <h3 class="archive-year">{{ .Key }}</h3>

            <ul class="archive-list">
                {{ range (where .Pages "Type" "post") }}
                    <li>
                        {{ .PublishDate.Format "2006-01-02" }}
                        -
                        <a href="{{ .RelPermalink }}">{{ .Title }}</a>
                    </li>
                {{ end }}
            </ul>
        {{ end }}
    </div>
</div>

<div class="container">
  {{ block "footer" . }}
    {{ partial "footer.html" . }}
  {{ end }}
</div>

</body>
</html>
```

This will mean that the head is correct, and it should fix a few issues I see on your site's version or at least this resolved those issues on my site after implementing.

**Pull request closed without merging**
