### PR TITLE
Improvement - Add last modified date display to list/single layouts

### PR DESCRIPTION
**Pull request by aormsby**
I was looking for a simple way to display the ‘last modified’ date, and I built a small feature to do it. If I can get some help with the last few pieces from someone, would you like to add it to your theme for others to use?

# How It Works
In both the `single` and `list` layouts, I’ve added a check for 2 parameters.
- `.LastModDisplay` (custom)
- `.LastMod`

I added an empty string `lastModDisplay` to the `config.toml` file. When it’s empty (or missing), nothing is displayed. If the user adds a string label - for example `lastModDisplay = “Modified: “` - then the text “Modified: [Jan 01, 0001]“ is displayed in post headers if `.LastMod` data exists.

# Three Things Missing - Please Help! 🙏 
`.GitInfo` use is not required but is a nice complement to this modified date feature.

However, when git info is enabled there is *always* going to be a `.LastMod` date available due to small differences between initial `.Date` data and modified commit info, so the `.LastMod` date will always be displayed even if it’s the same date.

I’d like to make 3 improvements to deal with issues that come from that. Since I’m still rather unfamiliar with the way Hugo uses Go, I’m looking for someone to help me implement them.

**Improvement 1** - Check if `.LastMod` is the same as`.Date`/`.PublishDate`. Ignore timestamp and only look at the date. Don’t display `.LastMod` if it’s the same day.

**Improvement 2** - If `.LastMod` is _before_ `.Date`/`.PublishDate`, don’t display `.LastMod`

**Improvement 3** - Is there is a simple way to disable the mod date display for main site pages that use the ”single” layout but still keep it visible on posts? [**Edit:** To be specific, this applies to pages where you want to have a creation date displayed, but you don't want to the last modified date to automatically display as well.]

The first two pieces seem super easy to check, but I honestly don’t know how to write comparative conditionals like that in Hugo’s layout files. I just haven’t seen any examples to show me how this works. I'm also not sure how best to approach the third part.

Can anyone help? I’d very much appreciate some guidance in completing this little feature.

—

I’ve also done a `yarn` build (hopefully correct!) and updated the README with the user details, and I can update it again with any further improvements.

Is there anything else I haven’t thought of? Please let me know what you think and if there’s anything else I should consider with this feature. Thanks! 😄

### CODE REVIEW

**Comment by panr** [comment]
Hi, @aormsby. Here's my solution: https://gist.github.com/panr/2166c51b11d4eb18e4f5c96350bc88fd

I simply added some conditionals to list and single (here I had to copy:
```
{{ $isntDefault := not (or (eq (trim $.Site.Params.contentTypeName " ") "posts") (eq (trim $.Site.Params.contentTypeName " ") "")) }}
{{ $contentTypeName := cond $isntDefault (string $.Site.Params.contentTypeName) "posts" }}
```
variables to make it work.)

Note that `lastmod.html` is a partial with internal logic.

PS: I think you don't need to have additional space in config after `Modified:`

**Comment by aormsby** [comment]
Sweet! **Improvement 2 & 3 are taken care of,** and I like the way you refactored a bit.

> PS: I think you don't need to have additional space in config after Modified:

Haha I see that. I don't even remember why I added it.

> PS2: Maybe it's just me, but I don't like float: right on modified date. I prefer wrapping it with parentheses (Modified: [Date])

Up to you. I may play around with it on my own build, but your take on it may be better for the base theme.

Thank you for guiding the way on things. I've noticed that just looking at golang documentation isn't quite enough to grasp how Hugo's scripts work, and it took me longer than I'd like to admit to understand that 'gt' stands for 'greater than'.

Only 2 things stand in the way now - I think **Improvement 1** isn't quite finished yet. I noticed that if I have git info enabled that my creation date and last mod git date could be the same at the **date** level, but different at the **time** level.

For example:
`publishDate: 2019-11-09T18:48:00+07:00`
` .     lastmod: 2019-11-09T18:50:00+07:00`

Since our current conditional doesn't account for that, we could get something like this: `Nov 09, 2019 (Modified: Nov 09, 2019)`. Not desirable. I'll look into it some.

The second thing is that I kind of screwed up my PR branch by merging a bunch of other things when I wasn't paying attention. I'll need to sort that out before I mark things ready for review. 😅

**Comment by panr** [comment]
> The second thing is that I kind of screwed up my PR branch by merging a bunch of other things when I wasn't paying attention. I'll need to sort that out before I mark things ready for review. 😅

OK, no problem here ;-)

> For example:
publishDate: 2019-11-09T18:48:00+07:00
. lastmod: 2019-11-09T18:50:00+07:00

> Since our current conditional doesn't account for that, we could get something like this: Nov 09, 2019 (Modified: Nov 09, 2019). Not desirable. I'll look into it some.

Hmm... maybe we could set some timeout window to deal with that... maybe 1h? Then any updates _after_ 1h will be print as `modified`? I know it's little naive, but...🤔 What do you think?

**Comment by aormsby** [comment]
> Hmm... maybe we could set some timeout window to deal with that... maybe 1h?

I guess that could work? The time limit feels rather arbitrary, though. I had initially thought about only adding the last mod if it was the next day or later when the updates were made, but then (hypothetically) a full 24 hours could pass where any modified pages wouldn't have the label. That's sort of the extreme other end compared to your 1 hour, though.

Here's a quick solution for the 'day' check: [https://gist.github.com/aormsby/06331c41253f6eee4ca7741cbdd8f3a7](https://gist.github.com/aormsby/06331c41253f6eee4ca7741cbdd8f3a7) Admittedly, it's a bit hacky to cut up the string like that, but I didn't know a better way to do it.

I'd say both of our solutions do deal with the issue, but I think in the end we're going to be haggling about how much time should pass before we say that a page would deserve to have a modified label. Is there any kind of 'time passed' standard that might guide us a bit?

**Comment by panr** [comment]
1h window should be fine I guess. As you said, 24h could be too extreme 😬
Also, there is a better solution to get right time format than slicing `.Date` — https://gohugo.io/functions/time/. ;-)

I'd go with something like `if gt (time .Lastmod).Unix (add (time .Date).Unix 3600000)` ¯\_(ツ)_/¯

**Comment by aormsby** [comment]
> Also, there is a better solution...

Haha I was sure there would be. I do need to spend some time looking through the Go documentation soon, that's for sure.

So 1 hour then. Cool. Do you think it's necessary to add a timestamp to the mod date in the case where it's the same date? I suppose it might look a bit weird to users to see the date repeated, but at the same time I'm not sure it's that important.

**Comment by aormsby** [comment]
Yay, it's ready! The Unix time function seems to need a check using  _seconds_, by the way. Not nanoseconds. So I used 3600 instead. Just a heads up on that.

Everything else is complete, and I even checked all the changes on a clean theme. Ready for you to review. :)

**Comment by aormsby** [comment]
I'll be adding some shortcode update suggestions in a bit, and I thought I'd drop a reminder notification here for you in case the last one was lost to the universe. All ready to go! 😸

**Comment by panr** [comment]
>  I thought I'd drop a reminder notification here for you in case the last one was lost to the universe. All ready to go! 

Ooops 😬 I really need some new routine to handle issues/PRs in all of my repos 🙉

**Comment by panr** [comment]
Merged! 🎉 Thanks ;-)

**Pull request merged**
