### PR TITLE
Add related posts, bio and tags cloud

### PR DESCRIPTION
**Pull request by michalchecinski**

### CODE REVIEW

**Comment by panr** [comment]
@michalchecinski I need more time to think about this PR ;-)

**Comment by michalchecinski** [comment]
Of course :)

**Comment by panr** [comment]
OK @michalchecinski, I'm afraid that we have to split this PR into smaller chunks. There are a lot of breaking changes... Could you send PR for each functionality separately? 🙏

**Comment by michalchecinski** [comment]
Yep, this could be done :)

**Pull request closed without merging**
