### PR TITLE
Add Stackbit Integration

### PR DESCRIPTION
**Pull request by RistoBIn**
This pull request add's Stackbit to this Hugo theme. It add's the stackbit.yaml file which makes this theme work with several headless CMS automatically (including Forestry, NetlifyCMS, DatoCMS & Contentful) and it deploys the site to Netlify in 1 click.

You can try it out: https://app.stackbit.com/create?theme=https://github.com/stackbithq/hugo-theme-hello-friend (note the "create with stackbit" button in the readme will import the theme from your repo so until the PR is merged it wont work)

I think this is really valuable and is a very low impact addition on your existing theme structure. Pretty much just the stackbit.yaml file. If you have questions or feedback I'm happy to discuss.

Risto

### CODE REVIEW

**Comment by aormsby** [comment]
@RistoBIn Hi, I have a question for you. In the .yaml file I see you set `ssgName: custom` as recommended by Stackbit docs), which specifically chooses 'Custom' in the Stackbit setup sequence but then prevents me from selecting Hugo.

Screen Shot 2019-11-03 at 16 10 01

However, you also set `buildCommand: cd exampleSite && hugo --gc --baseURL "/" --themesDir ../.. && cd ..` to specifically build with Hugo.

Is this contradictory at all? How does the Custom selection work compared to the Hugo selection? Would it be better to set `ssgName: hugo` if we're decidedly using Hugo as our SSG?

**Comment by RistoBIn** [comment]
Hello, Adam
Do you want to make custom theme based on Hugo?
Or need to use Stackbit theme?

The build command was made base on example directory.
That is why looks like that format.
Hope to know more details.
:)

**Comment by panr** [comment]
Maybe it's too late... but are we still interested in adding this? 🙄

**Comment by RistoBIn** [comment]
Adding is depend on your decision.
If you think that is useful, then you can add.

**Comment by panr** [comment]
Good question... My intention is to keep the theme as simple as possible, but also make everything I can to allow users use their favorite tools, extensions or setups.

From my point of view, this PR is not directly related to the theme itself - more to the user's deployment setup.

So maybe we could introduce this integration feature on a separate branch? We could create `integrations` branch and keep things like this on it? What do you think?

**Comment by RistoBIn** [comment]
Nice idea.

**Pull request closed without merging**
