### PR TITLE
Added ReadingTime indication to give the reader an idea of the read t…

### PR DESCRIPTION
**Pull request by mpaepper**
…ime in minutes

### CODE REVIEW

**Comment by mpaepper** [comment]
I think this is a nice feature and the ReadingTime variable is already populated by Hugo, so why not take advantage of it?

**Comment by jhabdas** [comment]
https://kodify.net/hugo/strings/reading-time-text/#calculate-the-read-time-of-text-in-minutes-and-seconds

**Comment by panr** [comment]
@mpaepper Good idea! But I think we need here some little changes ;-)

**Comment by mpaepper** [comment]
Hi @panr 
Sure, sounds good to me. I am happy to adjust it accordingly. 
Do you have a specific svg icon in mind that I should add?

**Comment by mpaepper** [comment]
@panr 
I added the suggested changes. Feel free to add an svg icon as you please.
Thanks!

**Comment by panr** [comment]
@mpaepper thanks! We're good to go ;-)

I thought about the icon... and decided to have no icon at all ;-P It looks cleaner for me 😬

**Pull request merged**
